version: '3'
services:
  app:
    volumes:
    - .:/usr/src/app 
    container_name: express-login
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'